### ISSUE TITLE
Shadow items unlink after reconnection

### ISSUE THREAD

**Issue by YTpooshistic** [ForwarD-NerN/AntiShadowPatch#13]
Shadow items unlink after reconnection

https://github.com/user-attachments/assets/edcc7821-defd-4c3f-a9d9-7258fc2e6fcd

**Comment by YTpooshistic** [comment]
On server after reconnection shadow items are duplicated too
https://github.com/user-attachments/assets/33217409-81a7-43bc-8c98-4a8a40a99025

**Comment by ForwarD-NerN** [comment]
Это не проблема AntiShadowPatch, а ванильное поведение. AntiShadowPatch лишь только добавляет те вещи, которые моджанги "зашедоупатчили" в версиях до этого. 

Для того чтобы они не разлинковывались можно использовать [Carpet Shadow](https://www.curseforge.com/minecraft/mc-mods/carpet-shadow). Правда его нет на 1.21.

_Я думал над тем чтобы сделать альтернативу Carpet Shadow, но потом понял сколько для этого нужно будет страдать при обновлении на новые версии(он ведь не просто так ещё не обновлён на 1.20.5+). + его принцип работы мне не очень нравится_
