### ISSUE TITLE
[Suggestion] Fix crafter and copper bulb

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [ForwarD-NerN/AntiShadowPatch#3]
Mostly title says everything. My suggestion is adding feature to reimplement 1 game tick delay to both crafter and copper bulb that was removed in 23w46a

**Comment by MrMasrozYTLIVE** [comment]
Lol?

**Comment by ForwarD-NerN** [comment]
Thanks for the suggestion! It's now a part of [NotSoShadowExtras](https://modrinth.com/mod/notsoshadowextras). As it isn't exactly a "shadow" patch.
