### ISSUE TITLE
[Question/Bug?] Functionality of the RedstoneWireBlockMixin

### ISSUE THREAD

**Issue by LemonatedCat** [ForwarD-NerN/AntiShadowPatch#4]
Currently attempting to reconstruct this mod for my Paper Server, and i ran into an issue with one of the Patches, or maybe i just do not understand it:

[RedstoneWireBlockMixin.](https://github.com/ForwarD-NerN/AntiShadowPatch/blob/master/src/main/java/ru/nern/antishadowpatch/mixin/block/updates/RedstoneWireBlockMixin.java#L17)

The Return value, and Operation, are a Boolean, but the actual Method returns a RedstoneSide, i'm probably just missing something but i'm curious about how/if it works

**Comment by MrMasrozYTLIVE** [comment]
[JavaDoc](https://javadoc.io/doc/io.github.llamalad7/mixinextras-fabric/latest/com/llamalad7/mixinextras/injector/wrapoperation/WrapOperation.html) & [Wiki](https://github.com/LlamaLad7/MixinExtras/wiki/WrapOperation)
This might help you understanding that thing. I think its just an IF check before original function is being called so like "If return is false - dont call original function"

**Comment by LemonatedCat** [comment]
Yep thanks, i figured out that it just affects the ? : operation before that, and the Trapdoor thing is not an instanceof check, it just targets the line with the instanceof. Thanks.

I have not managed to make it work fully on Paper, mostly because the crash handlers are near impossible to intercept, atleast it is throwing an error that is not caught though. will continue that some day.

**Comment by ForwarD-NerN** [comment]
As it's not an issue, I'll close it
