### ISSUE TITLE
[Bug] Infinite furnace xp bug also working without any suppresion

### ISSUE THREAD

**Issue by Notoriousi** [ForwarD-NerN/AntiShadowPatch#5]
I found an odd bug where infinite furnace xp just works whenever...
1. Place a furnace
2. smelt any item (take out with hopper perhaps optional)
3. Break the furnace (you get xp)
4. place the furnace
5. break the furnace (you get xp again)
6. repeat 4 & 5.
Video: https://youtu.be/ypxJEEyHR4Y
Log: https://mclo.gs/AxOFFUD (only used this and the extra mod, edited because wrong log)

**Comment by ForwarD-NerN** [comment]
Fixed in 1.0.7
