### ISSUE TITLE
can i create an EOL farm using the mod like i have the mod installed on the server so can i make a light suppressor in 1.20.1? for EOL farm?

### ISSUE THREAD

**Issue by Mint169** [ForwarD-NerN/AntiShadowPatch#7]
can i create an EOL farm using the mod like i have the mod installed on the server so can i make a light suppressor in 1.20.1? for EOL farm?

**Comment by ForwarD-NerN** [comment]
With this mod, you can't. The "Disable Light Recalculation DataFixer" option only allows you to convert existing worlds with EOL farms to 1.20 without them being broken. I think there's an option in Carpet TIS to suppress light updates

**Comment by Mint169** [comment]
but mobs dont spawn on portal blocks since 1.20 right ?,so by any chance do u know any mod that reverses the change?
