### ISSUE TITLE
Does not work on fabric server 1.20.4

### ISSUE THREAD

**Issue by blackdllx** [ForwarD-NerN/AntiShadowPatch#8]
crash fix works but nothing else does, i tried portal breaking  and shadow item

**Comment by ForwarD-NerN** [comment]
Can't seem to reproduce this issue. Maybe you're using a broken update suppressor? Try to use [Nicnac's](https://www.youtube.com/watch?v=hZEOyZ3CEXY) one

**Comment by blackdllx** [comment]
Doesn't work. My mod list: anti-shadow-patch-1.20.5-1.0.6.jar, carpet-fixes-1.20-1.17.0.jar, fabric-api-0.96.11+1.20.4.jar, fabric-carpet-1.20.3-1.4.128+v231205.jar, not-so-shadow-extras-1.20.4-1.0.2(1).jar

**Comment by blackdllx** [comment]
Any more ideas?

**Comment by ForwarD-NerN** [comment]
Seems like an incompatibility with Carpet Fixes. You can enable carpet-fixes reintroduceInstantBlockUpdates and it will work. All other features of AntiShadowPatch should also work without any problems
