### ISSUE TITLE
Does this work in Paper 1.8 singleplayer raid farm purpur sned money

### ISSUE THREAD

**Issue by BegleitPanzer** [ForwarD-NerN/AntiShadowPatch#9]
Does this work in Paper 1.8 singleplayer raid farm purpur sned money

**Comment by ForwarD-NerN** [comment]
Yes! But only if you join the server on bedrock at 5 am and use the trick that Ray's Works discovered

**Comment by BegleitPanzer** [comment]
Rays Works discovered minecraft right?

**Comment by ForwarD-NerN** [comment]
He discovered our universe
